### ISSUE TITLE
ignore 404s if PagePathHistory installed

### ISSUE THREAD

**Issue by PeterKnightDigital** [kixe/Process404Logger#1]
If you change the path / address of a page, Process404 logger will find log the old address as a 404.

It's correct that the page can't be found but as pages are automatically redirected using PagePathHistory,  it'd be great to hide these false positives from the log.

Great module. Thanks for making it.

**Comment by kixe** [comment]
If PagePathHistory is active and a page will be redirected Process404logger will not create a log entry. If the 404 page is shown for sure this should be logged. Nothing to hide. Everything is working properly. Cannot reproduce. Need some details.
