### ISSUE TITLE
Small fix proposal

### ISSUE THREAD

**Issue by foobarlab** [kixe/Process404Logger#2]
This is a really handy module. Thanks for that!

I get some error messages and as I am too lazy to start a PR I would recommend to change at least the following lines:

https://github.com/kixe/Process404Logger/blob/master/Process404Logger.module#L53
Remove the `$ready` variable, seems unused anyway. This causes an error for me (Index 2 is out of range if a 404 is set programmatically).

https://github.com/kixe/Process404Logger/blob/master/Process404Logger.module#L45
Add `HookEvent` in front of `$event` (rather cosmetic than a bug).

https://github.com/kixe/Process404Logger/blob/master/Process404Logger.module#L64
Add `$info="";` to avoid the fact that `$info` is never set (in some cases it is unititialized). This caused an error for me too. Best would be to set it to a default value like `$info="unknown cause";` to be able to track unhandled causes.

https://github.com/kixe/Process404Logger/blob/master/Process404Logger.module#L79
It would probably make sense if you can also limit the log size. Maybe https://processwire.com/talk/topic/1126-how-to-debug-use-the-error-log/?p=47164 helps.

Thanks, and keep up the good work!

**Comment by kixe** [comment]
Thanks for reporting. I will make the recommended changings soon except the last one since FileLog.php has some bugs with its prune() function.

**Comment by kixe** [comment]
FileLog.php issue is fixed now:
https://github.com/ryancramerdesign/ProcessWire/issues/1405
