### ISSUE TITLE
Error: Call to undefined method FileLog::pruneBytes()

### ISSUE THREAD

**Issue by matjazpotocnik** [kixe/Process404Logger#3]
(line 95 of \site\modules\Process404Logger\Process404Logger.module) PW 2.5.4 dev

**Comment by kixe** [comment]
Update PW to 2.7 minimum

**Comment by matjazpotocnik** [comment]
Maybe you could provide backward compatibility and use  $log->prune method if $log->pruneBytes does not exist?

**Comment by kixe** [comment]
done

**Comment by matjazpotocnik** [comment]
THX!
