### ISSUE TITLE
unknown cause

### ISSUE THREAD

**Issue by matjazpotocnik** [kixe/Process404Logger#4]
Hi!

Occasionally "unknow cause" is logged on some of the pages/urls. If I try with different browsers and on different computers from different IPs I never get this "error", page loads just fine. I'm logging page status, sometimes page has status 1 (statusOn), sometimes 5 (statusOn+statusLocked). How could I track down this error? Almost all of the unknown causes come from the google search engine.

**Comment by kixe** [comment]
I never had this on my sites. The module is triggered by core process ProcessPageView::pageNotFound.
If the page exists under the requested path, a template file is assigned and the page is viewable for the current user ProcessPageView::pageNotFound shouldn't be called. You should check your own settings or find out where the ProcessPageView::pageNotFound call is coming from.
You can try to comment out line 81 in Process404Logger:
// $request = $page->url;
to get the original request and then try to reach the page by clicking the link in /logs/view/...

**Comment by matjazpotocnik** [comment]
Thank you, now I'm logging both: $page->url and $event->arguments[1], will report my findings.

**Comment by matjazpotocnik** [comment]
$page->url is /existingurl/ and $event->arguments[1] is /existingurl/nonexistingurl/

nonexistingurl was active at some point in time, but the was then deleted.

**Comment by kixe** [comment]
Did you allow to use urlsegments in template of /existingurl/ but not in templatefile?

**Comment by matjazpotocnik** [comment]
Yes, urlsegments are allowed in the template of /existingurl/ and I'm throwing Wire404Exception() if UrlSegment1 is not what I expect.

**Comment by kixe** [comment]
Ok, thats why. To match this specific case I will change line 81 to:

```
if ($request != $page->url) $info = "request '$request' doesn't equal \$page->url '$page->url' [$pid]";
```

Could you try out this? Thanks.

**Comment by matjazpotocnik** [comment]
/myurl/test request '/myurl/test' doesn't equal $page->url '/myurl/' [1119]

Looks fine to me.
